// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/error.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Err represents a custom error with code, message and optional remarks
type Err struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Remarks       string                 `protobuf:"bytes,3,opt,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Err) Reset() {
	*x = Err{}
	mi := &file_proto_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Err) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Err) ProtoMessage() {}

func (x *Err) ProtoReflect() protoreflect.Message {
	mi := &file_proto_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Err.ProtoReflect.Descriptor instead.
func (*Err) Descriptor() ([]byte, []int) {
	return file_proto_error_proto_rawDescGZIP(), []int{0}
}

func (x *Err) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Err) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Err) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

// GRPCError represents a gRPC error with code, message and optional error details
type GRPCError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []*Err                 `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPCError) Reset() {
	*x = GRPCError{}
	mi := &file_proto_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPCError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPCError) ProtoMessage() {}

func (x *GRPCError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPCError.ProtoReflect.Descriptor instead.
func (*GRPCError) Descriptor() ([]byte, []int) {
	return file_proto_error_proto_rawDescGZIP(), []int{1}
}

func (x *GRPCError) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GRPCError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GRPCError) GetDetails() []*Err {
	if x != nil {
		return x.Details
	}
	return nil
}

// StrictErr represents a strict error structure for HTTP responses
type StrictErr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Remarks       string                 `protobuf:"bytes,3,opt,name=remarks,proto3" json:"remarks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrictErr) Reset() {
	*x = StrictErr{}
	mi := &file_proto_error_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrictErr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrictErr) ProtoMessage() {}

func (x *StrictErr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_error_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrictErr.ProtoReflect.Descriptor instead.
func (*StrictErr) Descriptor() ([]byte, []int) {
	return file_proto_error_proto_rawDescGZIP(), []int{2}
}

func (x *StrictErr) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StrictErr) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StrictErr) GetRemarks() string {
	if x != nil {
		return x.Remarks
	}
	return ""
}

var File_proto_error_proto protoreflect.FileDescriptor

const file_proto_error_proto_rawDesc = "" +
	"\n" +
	"\x11proto/error.proto\x12\x05proto\"M\n" +
	"\x03Err\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aremarks\x18\x03 \x01(\tR\aremarks\"_\n" +
	"\tGRPCError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\adetails\x18\x03 \x03(\v2\n" +
	".proto.ErrR\adetails\"S\n" +
	"\tStrictErr\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\aremarks\x18\x03 \x01(\tR\aremarksB$Z\"github.com/cozy-hub-app/proto/gen/gob\x06proto3"

var (
	file_proto_error_proto_rawDescOnce sync.Once
	file_proto_error_proto_rawDescData []byte
)

func file_proto_error_proto_rawDescGZIP() []byte {
	file_proto_error_proto_rawDescOnce.Do(func() {
		file_proto_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_error_proto_rawDesc), len(file_proto_error_proto_rawDesc)))
	})
	return file_proto_error_proto_rawDescData
}

var file_proto_error_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_error_proto_goTypes = []any{
	(*Err)(nil),       // 0: proto.Err
	(*GRPCError)(nil), // 1: proto.GRPCError
	(*StrictErr)(nil), // 2: proto.StrictErr
}
var file_proto_error_proto_depIdxs = []int32{
	0, // 0: proto.GRPCError.details:type_name -> proto.Err
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_error_proto_init() }
func file_proto_error_proto_init() {
	if File_proto_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_error_proto_rawDesc), len(file_proto_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_error_proto_goTypes,
		DependencyIndexes: file_proto_error_proto_depIdxs,
		MessageInfos:      file_proto_error_proto_msgTypes,
	}.Build()
	File_proto_error_proto = out.File
	file_proto_error_proto_goTypes = nil
	file_proto_error_proto_depIdxs = nil
}
